### ISSUE TITLE
More examples?

### ISSUE THREAD

**Issue by brahmafear** [bot779/ruckusconf#1]
Possible to update documentation / readme with some more examples of use?  For instance, how to download running config?  

Thanks.

**Comment by bot779** [comment]
There is an "--example" flag that shows examples.
"show config" was just added to the output of "--example".
(It's very similar to what used to be the first example)

Let me know if you see any other issues.

**Comment by brahmafear** [comment]
Thanks!  

When executing "ruckusconf --example" , I get the following output:

$ ./ruckusconf --example
Examples:
usage: send [args] string
    while executing
"send_user -- '  ./ruckusconf --password passw0rd --username admin --enable --command "show config" 192.168.3.180\n'"
    ("--example" arm line 3)
    invoked from within
"switch -- $flag {
    "--telnet" {
        set telnet true
        set argv [lrange $argv 1 end]
      }
    "--username" {
        set username [lind..."
    ("while" body line 3)
    invoked from within
"while { [llength $argv] > 0 } {
  set flag [lindex $argv 0]
  switch -- $flag {
    "--telnet" {
        set telnet true
        set argv [lrange $arg..."
    (file "./ruckusconf" line 97)

This is on both OSX 10.10.4 and Ubuntu 10.04.4.

**Comment by bot779** [comment]
This seems to be due to my total lack of understanding of how to escape quote characters in TCL and the fact that I cut+pasted my examples into the source without ever testing the --example option.

Thanks for pointing that out.
It should be fixed now.
