### ISSUE TITLE
Python errors on execution

### ISSUE THREAD

**Issue by brahmafear** [bot779/ruckusconf#2]
Invoking:
./ruckusconf --localdebug --username admin --password XXXX --command "help" 1.2.3.4

and getting this output:

argc = 1
can't read "intro": no such variable
    while executing
"concat $intro $commandlist section-context-mode $outro "
    ("while" body line 39)
    invoked from within
"while { $continueloop == "true" } {
  if { $loopprog == "" } {
    set continueloop false
  } else {
    if { [ catch {exec $loopprog} msg ] } {
     ..."
    (file "./ruckusconf" line 317)

Tried on python 2.7.10 on OSX 10.10.5 and 2.6.5 on Ubuntu 10.04.4

**Comment by bot779** [comment]
brahmafear:
Thanks for reporting this issue. I've replicated your problem.
This is a bug and I'll try to fix it soon.

In the meantime:
The commandline you gave (if it worked) wouldn't provide very meaningful results.
If you specify one of the options:
  --enable
  --configure
or
  --debug
along w/ the IP address of a ZD controller, you should avoid exercising this bug and get much more interesting results.

If you're trying to work w/ an AP directly, you should specify the --ap option.

Take a look at the "--examples" option if you want to see commandlines that are known to work.
If you have questions, I'll be in the #wireless channel on webchat.freenode.net for a little bit.

note:
ruckusconf works on RedHat distros and should work on other linuxes, Probably on MACs too.
(I haven't tested it on a macintosh)
These aren't python errors 'cause ruckusconf is written in TCL.

-Bill

**Comment by bot779** [comment]
..and it's fixed.
Please download the updated version and give it a try.
